// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCenter from "@/components/sections/contact/ContactCenter";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactCenter
                textAnimation="fade-blur"
                tag="Get in Touch"
                title="Ready to Transform Your Digital Presence?"
                description="Let's build something extraordinary together. Get in touch and let's discuss your next project."
                inputPlaceholder="Enter your email"
                buttonText="Start Your Project"
              />
            </div>
  );
}
