// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from "@/components/sections/faq/FaqSimple";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
              <FaqSimple
                textAnimation="fade-blur"
                tag="FAQ"
                title="Frequently Asked Questions"
                description="Everything you need to know about working with us."
                items={[
                  {
                    question: "How long does a typical project take?",
                    answer: "Most projects are completed within 2-4 weeks depending on scope and complexity. We'll provide a detailed timeline during our initial consultation.",
                  },
                  {
                    question: "What is your pricing structure?",
                    answer: "We offer project-based pricing tailored to your needs. Every project includes design, development, SEO optimization, and post-launch support.",
                  },
                  {
                    question: "Do you offer ongoing maintenance?",
                    answer: "Yes! We provide ongoing support and maintenance packages to keep your website updated, secure, and performing at its best.",
                  },
                  {
                    question: "Can you redesign my existing website?",
                    answer: "Absolutely. We specialize in website redesigns that modernize your brand while preserving your existing content and SEO rankings.",
                  },
                  {
                    question: "What technologies do you use?",
                    answer: "We build with modern technologies including Next.js, React, and Tailwind CSS to ensure fast, scalable, and maintainable websites.",
                  },
                ]}
              />
            </div>
  );
}
