// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from "@/components/sections/metrics/MetricsFeatureCards";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
              <MetricsFeatureCards
                textAnimation="fade-blur"
                tag="Results"
                title="Trusted by Industry Leaders"
                description="Years of experience building digital products that drive real results."
                metrics={[
                  {
                    value: "100+",
                    title: "Projects Delivered",
                    features: [
                      "E-commerce platforms",
                      "Corporate websites",
                      "SaaS applications",
                      "Mobile-first designs",
                    ],
                  },
                  {
                    value: "99%",
                    title: "Client Satisfaction",
                    features: [
                      "On-time delivery",
                      "Clear communication",
                      "Post-launch support",
                      "Ongoing partnerships",
                    ],
                  },
                  {
                    value: "8+",
                    title: "Years Experience",
                    features: [
                      "Industry expertise",
                      "Award-winning work",
                      "Global clientele",
                      "Proven methodology",
                    ],
                  },
                ]}
              />
            </div>
  );
}
