// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "promise" section.

import React from 'react';
import FeaturesBorderGlow from "@/components/sections/features/FeaturesBorderGlow";
import { Monitor, Zap, Shield, ArrowUpRight, Code, Palette, Layers, PenTool, Sparkles } from "lucide-react";

export default function PromiseSection(): React.JSX.Element {
  return (
    <div id="promise" data-section="promise">
              <FeaturesBorderGlow
                textAnimation="fade-blur"
                tag="Our Promise"
                title="Why Brands Choose Webild"
                description="We deliver results that speak for themselves."
                features={[
                  {
                    icon: Monitor,
                    title: "Responsive Design",
                    description: "Pixel-perfect websites that look stunning on every screen size and device.",
                  },
                  {
                    icon: Zap,
                    title: "Fast Turnaround",
                    description: "From concept to launch in record time without sacrificing quality.",
                  },
                  {
                    icon: Shield,
                    title: "Secure Hosting",
                    description: "Enterprise-grade security and 99.9% uptime for your website.",
                  },
                ]}
              />
            </div>
  );
}
