// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBento from "@/components/sections/features/FeaturesBento";
import { Monitor, Zap, Shield, ArrowUpRight, Code, Palette, Layers, PenTool, Sparkles } from "lucide-react";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesBento
                textAnimation="fade-blur"
                tag="Services"
                title="وش يساعدك فيه رَوّق؟"
                description="فيه كثير علامات اجهاد و إرهاق الي تعودنا اننا نتجاهلها حتى صارت جزء مننا"
                features={[
                  {
                    title: "Web Development",
                    description: "Custom-built websites that are fast, responsive, and designed to convert.",
                    bentoComponent: "checklist-timeline",
                    heading: "Project Timeline",
                    subheading: "Week 1-2",
                    checklistItems: [
                      { label: "Discovery & Strategy", detail: "Day 1-3" },
                      { label: "Design & Prototype", detail: "Day 4-7" },
                      { label: "Development & Launch", detail: "Day 8-14" },
                    ],
                    completedLabel: "Live",
                  },
                  {
                    title: "SEO Optimization",
                    description: "We optimize your website to rank higher on search engines and drive organic traffic.",
                    bentoComponent: "animated-bar-chart",
                  },
                  {
                    title: "Branding",
                    description: "Build a memorable brand identity that resonates with your audience.",
                    bentoComponent: "orbiting-icons",
                    centerIcon: Sparkles,
                    orbitIcons: [Palette, Layers, PenTool, Code],
                  },
                ]}
              />
            </div>
  );
}
