// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBento from "@/components/sections/features/FeaturesBento";
import { Monitor, Zap, Shield, ArrowUpRight, Code, Palette, Layers, PenTool, Sparkles } from "lucide-react";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesBento
                textAnimation="fade-blur"
                tag="Services"
                title="وش يساعدك فيه رَوّق؟"
                description="فيه كثير علامات اجهاد و إرهاق الي تعودنا اننا نتجاهلها حتى صارت جزء مننا"
                features={[
                  {
                    title: "Web Development",
                    description: "Custom-built websites that are fast, responsive, and designed to convert.",
                    image: "https://storage.googleapis.com/webild/users/user_3FtXGZmo2q34ph3RhCNPCt0XPUG/uploaded-1782903703652-iz2msjpg.png",
                  },
                  {
                    title: "SEO Optimization",
                    description: "We optimize your website to rank higher on search engines and drive organic traffic.",
                    image: "https://storage.googleapis.com/webild/users/user_3FtXGZmo2q34ph3RhCNPCt0XPUG/uploaded-1782903703653-1jqzp5px.png",
                  },
                  {
                    title: "Branding",
                    description: "Build a memorable brand identity that resonates with your audience.",
                    image: "https://storage.googleapis.com/webild/users/user_3FtXGZmo2q34ph3RhCNPCt0XPUG/uploaded-1782903703654-bv6ksmeq.png",
                  },
                ]}
              />
            </div>
  );
}
