// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamStackedCards from "@/components/sections/team/TeamStackedCards";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
              <TeamStackedCards
                textAnimation="fade-blur"
                tag="Team"
                title="The Team Behind the Work"
                description="The creative minds behind your next project."
                members={[
                  {
                    name: "Sarah Miller",
                    role: "Lead Developer",
                    imageSrc: "https://webuild-dev.s3.eu-north-1.amazonaws.com/default/templates/web-agency-2/team-1.webp?_wi=2",
                  },
                  {
                    name: "Valentina Reyes",
                    role: "Creative Director",
                    imageSrc: "https://webuild-dev.s3.eu-north-1.amazonaws.com/default/templates/web-agency-2/team-2.webp?_wi=2",
                  },
                  {
                    name: "Carlos Mendoza",
                    role: "UX Designer",
                    imageSrc: "https://webuild-dev.s3.eu-north-1.amazonaws.com/default/templates/web-agency-2/team-3.webp?_wi=2",
                  },
                ]}
              />
            </div>
  );
}
