// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "work" section.

import React from 'react';
import FeaturesMediaCarousel from "@/components/sections/features/FeaturesMediaCarousel";
import { Monitor, Zap, Shield, ArrowUpRight, Code, Palette, Layers, PenTool, Sparkles } from "lucide-react";

export default function WorkSection(): React.JSX.Element {
  return (
    <div id="work" data-section="work">
              <FeaturesMediaCarousel
                textAnimation="fade-blur"
                tag="Our Work"
                title="Work We're Proud Of"
                description="A selection of projects we've crafted for clients across industries."
                items={[
                  {
                    title: "Vitality Wellness",
                    description: "Health & wellbeing platform",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/projectnew1.webp",
                    buttonIcon: ArrowUpRight,
                    buttonHref: "#",
                  },
                  {
                    title: "Mailflow AI",
                    description: "AI-powered email marketing platform",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/projectnew2.webp",
                    buttonIcon: ArrowUpRight,
                    buttonHref: "#",
                  },
                  {
                    title: "Kinetic Studios",
                    description: "Motion graphics & visual effects",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/projectnew3.webp",
                    buttonIcon: ArrowUpRight,
                    buttonHref: "#",
                  },
                ]}
              />
            </div>
  );
}
